import type { ContractMeta } from "@/app/third-party-contracts/types"

export type GrunenthalGrtContractDocument = {
  id: string
  slug: string
  sourceName: string
  fileName: string
  displayName: string
  path: string
  previewPdfPath: string
  previewPageImagePaths?: string[]
  extension: "pdf" | "docx"
  mimeType: string
  size: number
  providerIdentity: string
  area: string
  contractObject: string
  communicationType: string
  relationType: string
  clauseComplianceStatus: NonNullable<ContractMeta["clauseComplianceStatus"]>
  clauseComplianceLabel: string
  clauseType: string
  analysisSummary: string
  recommendation: string
  riskLevel: ContractMeta["riskLevel"]
  documentKind: string
}

const MASTER_CONTROL_PREVIEW_IMAGE_PATHS = Array.from(
  { length: 50 },
  (_, index) =>
    `/client/grunenthal/third-party-contracts/contratos-grt/previews/contract-mastercontrol/page-${String(
      index + 1,
    ).padStart(2, "0")}.jpg`,
)

export const GRUNENTHAL_GRT_CONTRACT_DOCUMENTS: GrunenthalGrtContractDocument[] = [
  {
    id: "grunenthal-grt-contract-002-03-09-2023-hays-ag-general-services-agreements-1-2",
    slug: "03-09-2023-hays-ag-general-services-agreements-1-2",
    sourceName: "03_09_2023_HAYS AG_General Services Agreements_1 (2).Pdf",
    fileName: "03-09-2023-hays-ag-general-services-agreements-1-2.pdf",
    displayName: "03_09_2023_HAYS AG_General Services Agreements_1 (2)",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/03-09-2023-hays-ag-general-services-agreements-1-2.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/03-09-2023-hays-ag-general-services-agreements-1-2.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 1880112,
    providerIdentity: "HAYS - AG",
    area: "Human Resources",
    contractObject: "Servicios de reclutamiento de personal.",
    communicationType: "transferencia",
    relationType: "tercero",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "§ 2 Geheimhaltung / Datenschutz",
    analysisSummary: "La cláusula no cumple con los requisitos locales identificados en el análisis.",
    recommendation: "Incorporar cláusula C2 o apéndice CM-2 para transferencia.",
    riskLevel: "medio",
    documentKind: "Contrato de servicios",
  },
  {
    id: "grunenthal-grt-contract-003-04-02-2025-gointegro-mexico-sa-de-cv-1",
    slug: "04-02-2025-gointegro-mexico-sa-de-cv-1",
    sourceName: "04_02_2025_GOINTEGRO MEXICO SA DE CV__1.Pdf",
    fileName: "04-02-2025-gointegro-mexico-sa-de-cv-1.pdf",
    displayName: "04_02_2025_GOINTEGRO MEXICO SA DE CV__1",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/04-02-2025-gointegro-mexico-sa-de-cv-1.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/04-02-2025-gointegro-mexico-sa-de-cv-1.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 279646,
    providerIdentity: "GOINTEGRO MÉXICO, S.A. DE C.V.",
    area: "Human Resources",
    contractObject: "Suscripción de plataforma Grunetemex.",
    communicationType: "remision",
    relationType: "encargado",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "Cláusula de protección de datos revisada en análisis fuente.",
    analysisSummary: "El análisis fuente marca incumplimiento para la relación de remisión.",
    recommendation: "Incorporar cláusula C1 o apéndice CM-1.",
    riskLevel: "medio",
    documentKind: "Contrato / evidencia",
  },
  {
    id: "grunenthal-grt-contract-004-06-16-2025-fuo-servicios-s-a-de-c-v-1",
    slug: "06-16-2025-fuo-servicios-s-a-de-c-v-1",
    sourceName: "06_16_2025_FUO SERVICIOS S.A. DE C.V__1.Pdf",
    fileName: "06-16-2025-fuo-servicios-s-a-de-c-v-1.pdf",
    displayName: "06_16_2025_FUO SERVICIOS S.A. DE C.V__1",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/06-16-2025-fuo-servicios-s-a-de-c-v-1.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/06-16-2025-fuo-servicios-s-a-de-c-v-1.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 2010875,
    providerIdentity: "FUO SERVICIOS, S.A. DE C.V.",
    area: "Human Resources",
    contractObject: "Servicios especializados de seguridad, resguardo y vigilancia.",
    communicationType: "mixta",
    relationType: "mixta",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "Cláusula de protección de datos revisada en análisis fuente.",
    analysisSummary: "La relación se considera mixta y requiere reforzar obligaciones de encargado y tercero.",
    recommendation: "Usar cláusulas C1 y C2 o apéndices CM-1/CM-2.",
    riskLevel: "alto",
    documentKind: "Contrato firmado",
  },
  {
    id: "grunenthal-grt-contract-005-10-cuesta-y-llaca-oc-4500790698-08-05-2025",
    slug: "10-cuesta-y-llaca-oc-4500790698-08-05-2025",
    sourceName: "10 Cuesta y Llaca OC 4500790698 - 08.05.2025.PDF",
    fileName: "10-cuesta-y-llaca-oc-4500790698-08-05-2025.pdf",
    displayName: "10 Cuesta y Llaca OC 4500790698 - 08.05.2025",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/10-cuesta-y-llaca-oc-4500790698-08-05-2025.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/10-cuesta-y-llaca-oc-4500790698-08-05-2025.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 69948,
    providerIdentity: "CUESTA Y LLACA SC",
    area: "Human Resources",
    contractObject: "Trámite migratorio.",
    communicationType: "remision",
    relationType: "encargado",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "Orden de compra vinculada a servicio analizado.",
    analysisSummary: "La evidencia corresponde a OC; debe acompañarse del instrumento con cláusula de encargado.",
    recommendation: "Vincular contrato o cláusula C1/CM-1.",
    riskLevel: "medio",
    documentKind: "Orden de compra",
  },
  {
    id: "grunenthal-grt-contract-006-11-07-2024-central-media-sc-1",
    slug: "11-07-2024-central-media-sc-1",
    sourceName: "11_07_2024_CENTRAL MEDIA SC__1.Pdf",
    fileName: "11-07-2024-central-media-sc-1.pdf",
    displayName: "11_07_2024_CENTRAL MEDIA SC__1",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/11-07-2024-central-media-sc-1.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/11-07-2024-central-media-sc-1.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 2886162,
    providerIdentity: "CENTRAL MEDIA, S.C.",
    area: "Digital",
    contractObject: "Servicios de creación de contenido para Grünenthal.",
    communicationType: "remision",
    relationType: "encargado",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "Vigésimo. Protección de datos personales",
    analysisSummary: "La falta o insuficiencia de cláusula puede afectar el principio de responsabilidad.",
    recommendation: "Usar cláusula C1 o apéndice CM-1.",
    riskLevel: "medio",
    documentKind: "Contrato firmado",
  },
  {
    id: "grunenthal-grt-contract-007-11-09-2024-bespoke-advertising-sa-de-cv-1",
    slug: "11-09-2024-bespoke-advertising-sa-de-cv-1",
    sourceName: "11_09_2024_BESPOKE ADVERTISING SA DE CV__1.Pdf",
    fileName: "11-09-2024-bespoke-advertising-sa-de-cv-1.pdf",
    displayName: "11_09_2024_BESPOKE ADVERTISING SA DE CV__1",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/11-09-2024-bespoke-advertising-sa-de-cv-1.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/11-09-2024-bespoke-advertising-sa-de-cv-1.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 1832396,
    providerIdentity: "BESPOKE ADVERTISING, S.A. DE C.V.",
    area: "Digital",
    contractObject: "Servicios de marketing y publicidad.",
    communicationType: "remision",
    relationType: "encargado",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "Vigésima Segunda. Protección de Datos Personales",
    analysisSummary: "La cláusula no cumple con los requisitos revisados en el análisis fuente.",
    recommendation: "Usar cláusula C1 o apéndice CM-1.",
    riskLevel: "medio",
    documentKind: "Contrato firmado",
  },
  {
    id: "grunenthal-grt-contract-009-11-15-2024-servicios-de-nomina-alfaplus-1",
    slug: "11-15-2024-servicios-de-nomina-alfaplus-1",
    sourceName: "11_15_2024_SERVICIOS DE NOMINA ALFAPLUS__1.Pdf",
    fileName: "11-15-2024-servicios-de-nomina-alfaplus-1.pdf",
    displayName: "11_15_2024_SERVICIOS DE NOMINA ALFAPLUS__1",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/11-15-2024-servicios-de-nomina-alfaplus-1.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/11-15-2024-servicios-de-nomina-alfaplus-1.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 2212257,
    providerIdentity: "ALPHAPLUS, S.A. DE C.V.",
    area: "Human Resources",
    contractObject: "Servicios de nómina y recursos humanos.",
    communicationType: "remision",
    relationType: "encargado",
    clauseComplianceStatus: "cumple",
    clauseComplianceLabel: "Sí cumple",
    clauseType: "Cláusula de protección de datos revisada en análisis fuente.",
    analysisSummary: "La cláusula cumple con los requisitos del análisis fuente.",
    recommendation: "Mantener evidencia y revisión anual.",
    riskLevel: "bajo",
    documentKind: "Contrato firmado",
  },
  {
    id: "grunenthal-grt-contract-010-11-15-2024-toka-internacional-s-a-p-i-de-c-v-1",
    slug: "11-15-2024-toka-internacional-s-a-p-i-de-c-v-1",
    sourceName: "11_15_2024_TOKA INTERNACIONAL S.A.P.I DE C.V__1.Pdf",
    fileName: "11-15-2024-toka-internacional-s-a-p-i-de-c-v-1.pdf",
    displayName: "11_15_2024_TOKA INTERNACIONAL S.A.P.I DE C.V__1",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/11-15-2024-toka-internacional-s-a-p-i-de-c-v-1.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/11-15-2024-toka-internacional-s-a-p-i-de-c-v-1.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 1802623,
    providerIdentity: "TOKA INTERNACIONAL, S.A.P.I. DE C.V.",
    area: "Human Resources",
    contractObject: "Dispersión, carga y recarga de recursos económicos.",
    communicationType: "transferencia",
    relationType: "tercero",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "(1) Confidencialidad",
    analysisSummary:
      "La cláusula y anexo establecen que la comunicación de datos es una remisión, lo cual es incorrecto, ya que al tener que cumplir obligaciones en materia de prevención de lavado de dinero de manera independiente a GRT se deberá de establecer como transferencia de datos personales. Se sugiere emplear la cláusula C2 del Manual de Relaciones con Terceros y/o en su caso, los apéndices 2 CM-2 o 3 C-2 del mismo donde se establece la relación entre las partes y sus obligaciones respectivas.",
    recommendation:
      "La cláusula y anexo establecen que la comunicación de datos es una remisión, lo cual es incorrecto, ya que al tener que cumplir obligaciones en materia de prevención de lavado de dinero de manera independiente a GRT se deberá de establecer como transferencia de datos personales. Se sugiere emplear la cláusula C2 del Manual de Relaciones con Terceros y/o en su caso, los apéndices 2 CM-2 o 3 C-2 del mismo donde se establece la relación entre las partes y sus obligaciones respectivas.",
    riskLevel: "medio",
    documentKind: "Contrato firmado",
  },
  {
    id: "grunenthal-grt-contract-011-12-contrato-safedata-resources",
    slug: "12-contrato-safedata-resources",
    sourceName: "12 Contrato SafeData Resources.pdf",
    fileName: "12-contrato-safedata-resources.pdf",
    displayName: "12 Contrato SafeData Resources",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/12-contrato-safedata-resources.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/12-contrato-safedata-resources.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 1578482,
    providerIdentity: "SAFE DATA RESOURCES, S.A. DE C.V.",
    area: "Human Resources",
    contractObject: "Contrato de depósito.",
    communicationType: "remision",
    relationType: "encargado",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "Vigésima. Protección de Datos Personales",
    analysisSummary: "Se sugieren cláusulas para remisión y transferencia de datos de empleados del proveedor.",
    recommendation: "Usar C1/CM-1 para remisión y C2/CM-2 si hay transferencia.",
    riskLevel: "medio",
    documentKind: "Contrato firmado",
  },
  {
    id: "grunenthal-grt-contract-012-12-safe-data-oc-4500798862-18-07-2025",
    slug: "12-safe-data-oc-4500798862-18-07-2025",
    sourceName: "12 Safe Data OC 4500798862 - 18.07.2025.PDF",
    fileName: "12-safe-data-oc-4500798862-18-07-2025.pdf",
    displayName: "12 Safe Data OC 4500798862 - 18.07.2025",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/12-safe-data-oc-4500798862-18-07-2025.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/12-safe-data-oc-4500798862-18-07-2025.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 69948,
    providerIdentity: "SAFE DATA RESOURCES, S.A. DE C.V.",
    area: "Human Resources",
    contractObject: "Orden de compra asociada a contrato de depósito.",
    communicationType: "remision",
    relationType: "encargado",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "Orden de compra vinculada a servicio analizado.",
    analysisSummary: "La OC sirve como evidencia operativa, pero el análisis debe soportarse en contrato/cláusulas.",
    recommendation: "Vincular contrato y apéndice C1/CM-1.",
    riskLevel: "medio",
    documentKind: "Orden de compra",
  },
  {
    id: "grunenthal-grt-contract-013-13-contrato-servicios-betterfly-grunenthal-v-23-09-2024-c-o-firmado",
    slug: "13-contrato-servicios-betterfly-grunenthal-v-23-09-2024-c-o-firmado",
    sourceName: "13 Contrato Servicios Betterfly - Grunenthal (V.23.09.2024 C.O) - firmado.pdf",
    fileName: "13-contrato-servicios-betterfly-grunenthal-v-23-09-2024-c-o-firmado.pdf",
    displayName: "13 Contrato Servicios Betterfly - Grunenthal (V.23.09.2024 C.O) - firmado",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/13-contrato-servicios-betterfly-grunenthal-v-23-09-2024-c-o-firmado.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/13-contrato-servicios-betterfly-grunenthal-v-23-09-2024-c-o-firmado.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 2641718,
    providerIdentity: "BETERFLY MÉXICO, S.A. DE C.V.",
    area: "Human Resources",
    contractObject: "Plataforma de beneficios de bienestar para trabajadores.",
    communicationType: "transferencia",
    relationType: "tercero",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType:
      "(1). Vigésima Primera. Protección de Datos Personales. (2). Anexo 3. Contrato de Procesamiento de Datos. (3) Convenio de Confidencialidad.",
    analysisSummary:
      "La cláusula y anexo establecen que la comunicación de datos es una remisión, lo cual es incorrecto, ya que al ofrecer servicios Telemedicina y otros servicios independientes y ajenos a Grünenthal se debe de considerar como una transferencia de datos personales. Se sugiere emplear la cláusula C2 del Manual de Relaciones con Terceros y/o en su caso, los apéndices 2 CM-2 o 3 C-2 del mismo donde se establece la relación entre las partes y sus obligaciones respectivas.",
    recommendation:
      "La cláusula y anexo establecen que la comunicación de datos es una remisión, lo cual es incorrecto, ya que al ofrecer servicios Telemedicina y otros servicios independientes y ajenos a Grünenthal se debe de considerar como una transferencia de datos personales. Se sugiere emplear la cláusula C2 del Manual de Relaciones con Terceros y/o en su caso, los apéndices 2 CM-2 o 3 C-2 del mismo donde se establece la relación entre las partes y sus obligaciones respectivas.",
    riskLevel: "medio",
    documentKind: "Contrato de servicios",
  },
  {
    id: "grunenthal-grt-contract-014-13-nda-betterfly-mexico-firmado",
    slug: "13-nda-betterfly-mexico-firmado",
    sourceName: "13 NDA Betterfly México - firmado.pdf",
    fileName: "13-nda-betterfly-mexico-firmado.pdf",
    displayName: "13 NDA Betterfly México - firmado",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/13-nda-betterfly-mexico-firmado.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/13-nda-betterfly-mexico-firmado.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 423275,
    providerIdentity: "BETERFLY MÉXICO, S.A. DE C.V.",
    area: "Human Resources",
    contractObject: "NDA asociado a servicios Betterfly.",
    communicationType: "transferencia",
    relationType: "tercero",
    clauseComplianceStatus: "requiere_revision",
    clauseComplianceLabel: "Requiere revisión",
    clauseType: "NDA / confidencialidad",
    analysisSummary: "El NDA no sustituye el instrumento de protección de datos requerido para la transferencia.",
    recommendation: "Vincular con contrato de servicios y cláusula C2/CM-2.",
    riskLevel: "medio",
    documentKind: "NDA",
  },
  {
    id: "grunenthal-grt-contract-015-2-contrato-alfa-firmado",
    slug: "2-contrato-alfa-firmado",
    sourceName: "2 Contrato Alfa - firmado.pdf",
    fileName: "2-contrato-alfa-firmado.pdf",
    displayName: "2 Contrato Alfa - firmado",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/2-contrato-alfa-firmado.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/2-contrato-alfa-firmado.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 2122492,
    providerIdentity: "ALPHAPLUS, S.A. DE C.V.",
    area: "Human Resources",
    contractObject: "Servicios de nómina y recursos humanos.",
    communicationType: "remision",
    relationType: "encargado",
    clauseComplianceStatus: "cumple",
    clauseComplianceLabel: "Sí cumple",
    clauseType: "Cláusula de protección de datos revisada en análisis fuente.",
    analysisSummary: "La cláusula cumple con los requisitos del análisis fuente.",
    recommendation: "Mantener evidencia y revisión anual.",
    riskLevel: "bajo",
    documentKind: "Contrato firmado",
  },
  {
    id: "grunenthal-grt-contract-016-3-ejemplo-oc-mp-executive-hunt-4500787886",
    slug: "3-ejemplo-oc-mp-executive-hunt-4500787886",
    sourceName: "3 Ejemplo OC MP Executive Hunt 4500787886.pdf",
    fileName: "3-ejemplo-oc-mp-executive-hunt-4500787886.pdf",
    displayName: "3 Ejemplo OC MP Executive Hunt 4500787886",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/3-ejemplo-oc-mp-executive-hunt-4500787886.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/3-ejemplo-oc-mp-executive-hunt-4500787886.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 72087,
    providerIdentity: "MP EXECUTIVE HUNT SA DE CV",
    area: "Human Resources",
    contractObject: "Búsqueda de representante CDMX/EM.",
    communicationType: "transferencia",
    relationType: "tercero",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "Orden de compra vinculada a servicio analizado.",
    analysisSummary: "La OC evidencia el servicio, pero debe vincularse al instrumento de transferencia.",
    recommendation: "Vincular cláusula C2/CM-2.",
    riskLevel: "medio",
    documentKind: "Orden de compra",
  },
  {
    id: "grunenthal-grt-contract-017-4-contrato-bacher-zoppi-s-a-de-c-v-firmado",
    slug: "4-contrato-bacher-zoppi-s-a-de-c-v-firmado",
    sourceName: "4 Contrato BACHER ZOPPI, S.A. DE C.V. - firmado.pdf",
    fileName: "4-contrato-bacher-zoppi-s-a-de-c-v-firmado.pdf",
    displayName: "4 Contrato BACHER ZOPPI, S.A. DE C.V. - firmado",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/4-contrato-bacher-zoppi-s-a-de-c-v-firmado.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/4-contrato-bacher-zoppi-s-a-de-c-v-firmado.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 3235963,
    providerIdentity: "BACHER ZOPPI, S.A. DE C.V.",
    area: "Human Resources",
    contractObject: "Servicios especializados relacionados a recursos humanos.",
    communicationType: "mixta",
    relationType: "mixta",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "Vigésima. Protección de Datos Personales",
    analysisSummary: "Las cláusulas no cumplen con los requisitos de la LFPDPPP y su Reglamento para una relación mixta.",
    recommendation: "Usar cláusulas C1 y C2 o apéndices CM-1/CM-2.",
    riskLevel: "alto",
    documentKind: "Contrato firmado",
  },
  {
    id: "grunenthal-grt-contract-018-6-contrato-caja-de-ahorro-fondo-de-garantia-sura-investment",
    slug: "6-contrato-caja-de-ahorro-fondo-de-garantia-sura-investment",
    sourceName: "6 Contrato Caja de Ahorro - Fondo de Garantía SURA Investment.pdf",
    fileName: "6-contrato-caja-de-ahorro-fondo-de-garantia-sura-investment.pdf",
    displayName: "6 Contrato Caja de Ahorro - Fondo de Garantía SURA Investment",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/6-contrato-caja-de-ahorro-fondo-de-garantia-sura-investment.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/6-contrato-caja-de-ahorro-fondo-de-garantia-sura-investment.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 7664732,
    providerIdentity: "SURA INVESTMENT MANAGEMENT MEXICO, S.A. DE C.V.",
    area: "Human Resources",
    contractObject: "Comisión mercantil y prestación de servicios para caja de ahorro / fondo de garantía.",
    communicationType: "transferencia",
    relationType: "tercero",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "Cláusula de protección de datos revisada en análisis fuente.",
    analysisSummary: "La transferencia requiere reforzar el instrumento contractual.",
    recommendation: "Usar cláusula C2 o apéndice CM-2.",
    riskLevel: "medio",
    documentKind: "Contrato firmado",
  },
  {
    id: "grunenthal-grt-contract-019-7-valmex-365346-grunenthal-copia-del-contrato",
    slug: "7-valmex-365346-grunenthal-copia-del-contrato",
    sourceName: "7 VALMEX 365346_GRÜNENTHAL_COPIA DEL CONTRATO.pdf",
    fileName: "7-valmex-365346-grunenthal-copia-del-contrato.pdf",
    displayName: "7 VALMEX 365346_GRÜNENTHAL_COPIA DEL CONTRATO",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/7-valmex-365346-grunenthal-copia-del-contrato.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/7-valmex-365346-grunenthal-copia-del-contrato.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 5101158,
    providerIdentity: "VALMEX",
    area: "Human Resources",
    contractObject: "Servicio financiero o administración de beneficios asociado a personal.",
    communicationType: "transferencia",
    relationType: "tercero",
    clauseComplianceStatus: "requiere_revision",
    clauseComplianceLabel: "Requiere revisión",
    clauseType: "Contrato escaneado sin texto extraíble suficiente.",
    analysisSummary: "No se localizó análisis directo en el compilado; requiere revisión jurídica antes de cerrar cumplimiento.",
    recommendation: "Registrar dictamen específico y validar cláusulas de transferencia.",
    riskLevel: "medio",
    documentKind: "Contrato escaneado",
  },
  {
    id: "grunenthal-grt-contract-020-8-dhl-oc-4500798860-18-07-2025",
    slug: "8-dhl-oc-4500798860-18-07-2025",
    sourceName: "8 DHL OC 4500798860 - 18.07.2025.PDF",
    fileName: "8-dhl-oc-4500798860-18-07-2025.pdf",
    displayName: "8 DHL OC 4500798860 - 18.07.2025",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/8-dhl-oc-4500798860-18-07-2025.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/8-dhl-oc-4500798860-18-07-2025.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 69680,
    providerIdentity: "DHL EXPRESS MEXICO SA DE CV",
    area: "Human Resources",
    contractObject: "Compra general de productos y mensajería nacional.",
    communicationType: "transferencia",
    relationType: "tercero",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "Orden de compra vinculada a servicio analizado.",
    analysisSummary: "La evidencia corresponde a OC; debe acompañarse de instrumento con cláusula aplicable.",
    recommendation: "Vincular contrato y cláusula C2/CM-2 si hay transferencia.",
    riskLevel: "medio",
    documentKind: "Orden de compra",
  },
  {
    id: "grunenthal-grt-contract-021-9-convenio-consultores-y-asesores-fpm-s-c-firmado",
    slug: "9-convenio-consultores-y-asesores-fpm-s-c-firmado",
    sourceName: "9 Convenio CONSULTORES Y ASESORES FPM, S.C. - firmado.pdf",
    fileName: "9-convenio-consultores-y-asesores-fpm-s-c-firmado.pdf",
    displayName: "9 Convenio CONSULTORES Y ASESORES FPM, S.C. - firmado",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/9-convenio-consultores-y-asesores-fpm-s-c-firmado.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/9-convenio-consultores-y-asesores-fpm-s-c-firmado.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 379102,
    providerIdentity: "NEGOCIOS DE INNOVACIÓN FARMACÉUTICA, S.C.",
    area: "COMEX",
    contractObject: "Servicios legales, consultoría, mercadotecnia, asesoría, marcas, inteligencia competitiva y capacitación.",
    communicationType: "remision",
    relationType: "encargado",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "(1) Vigésima. Protección de Datos Personales",
    analysisSummary:
      "Las cláusulas no cumplen con los requisitos de la LFPDPPP y su Reglamento. Se sugiere emplear la cláusula C1 del Manual de Relaciones con Terceros y/o en su caso, los apéndices 2 CM-1 o 3 C-1 del mismo donde se delimitan con amplio detalle las obligaciones del Encargado.",
    recommendation:
      "Las cláusulas no cumplen con los requisitos de la LFPDPPP y su Reglamento. Se sugiere emplear la cláusula C1 del Manual de Relaciones con Terceros y/o en su caso, los apéndices 2 CM-1 o 3 C-1 del mismo donde se delimitan con amplio detalle las obligaciones del Encargado.",
    riskLevel: "medio",
    documentKind: "Adendum contractual",
  },
  {
    id: "grunenthal-grt-contract-022-an-eversana-company-is-requesting-your-signat-1",
    slug: "an-eversana-company-is-requesting-your-signat-1",
    sourceName: "An_EVERSANA_Company_is_Requesting_Your_Signat (1).pdf",
    fileName: "an-eversana-company-is-requesting-your-signat-1.pdf",
    displayName: "An_EVERSANA_Company_is_Requesting_Your_Signat (1)",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/an-eversana-company-is-requesting-your-signat-1.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/an-eversana-company-is-requesting-your-signat-1.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 634517,
    providerIdentity: "EVERSANA, IRELAND, LIMITED",
    area: "Globales",
    contractObject: "Servicios vinculados al acuerdo de protección de datos.",
    communicationType: "remision",
    relationType: "encargado",
    clauseComplianceStatus: "cumple",
    clauseComplianceLabel: "Sí cumple",
    clauseType: "Acuerdo de protección de datos / firma",
    analysisSummary: "El análisis fuente marca cumplimiento para el acuerdo de servicios/DPA.",
    recommendation: "Mantener evidencia y revisión anual.",
    riskLevel: "bajo",
    documentKind: "DPA / evidencia de firma",
  },
  {
    id: "grunenthal-grt-contract-023-contrato-gointegro-mexico-s-a-de-c-v",
    slug: "contrato-gointegro-mexico-s-a-de-c-v",
    sourceName: "Contrato GOINTEGRO MEXICO S.A. DE C.V.pdf",
    fileName: "contrato-gointegro-mexico-s-a-de-c-v.pdf",
    displayName: "Contrato GOINTEGRO MEXICO S.A. DE C.V",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/contrato-gointegro-mexico-s-a-de-c-v.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/contrato-gointegro-mexico-s-a-de-c-v.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 2152576,
    providerIdentity: "GOINTEGRO MÉXICO, S.A. DE C.V.",
    area: "Human Resources",
    contractObject: "Suscripción de plataforma Grunetemex.",
    communicationType: "remision",
    relationType: "encargado",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "Cláusula de protección de datos revisada en análisis fuente.",
    analysisSummary: "El análisis fuente marca incumplimiento para la relación de remisión.",
    recommendation: "Incorporar cláusula C1 o apéndice CM-1.",
    riskLevel: "medio",
    documentKind: "Contrato firmado",
  },
  {
    id: "grunenthal-grt-contract-024-contrato-grt-ups-version-final-10-31-2022-signed",
    slug: "contrato-grt-ups-version-final-10-31-2022-signed",
    sourceName: "Contrato GRT-UPS Versión Final 10-31-2022 - signed.pdf",
    fileName: "contrato-grt-ups-version-final-10-31-2022-signed.pdf",
    displayName: "Contrato GRT-UPS Versión Final 10-31-2022 - signed",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/contrato-grt-ups-version-final-10-31-2022-signed.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/contrato-grt-ups-version-final-10-31-2022-signed.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 2142188,
    providerIdentity: "UPS SCS (MÉXICO), S.A. DE C.V.",
    area: "Supply",
    contractObject: "Almacenamiento, embalaje, surtido, empaque y preparación de pedidos.",
    communicationType: "transferencia",
    relationType: "tercero",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "(1) VIGÉSIMA PRIMERA. MANEJO DE DATOS PERSONALES",
    analysisSummary:
      "La cláusula no cumple con los requisitos de la LFPDPPP. Se sugiere emplear la cláusula C2 del Manual de Relaciones con Terceros y/o en su caso, los apéndices 2 CM-2 o 3 C-2 del mismo donde se establece la relación entre las partes y sus obligaciones respectivas",
    recommendation:
      "La cláusula no cumple con los requisitos de la LFPDPPP. Se sugiere emplear la cláusula C2 del Manual de Relaciones con Terceros y/o en su caso, los apéndices 2 CM-2 o 3 C-2 del mismo donde se establece la relación entre las partes y sus obligaciones respectivas",
    riskLevel: "medio",
    documentKind: "Contrato firmado",
  },
  {
    id: "grunenthal-grt-contract-025-contrato-sinergis-1",
    slug: "contrato-sinergis-1",
    sourceName: "Contrato Sinergis (1).pdf",
    fileName: "contrato-sinergis-1.pdf",
    displayName: "Contrato Sinergis (1)",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/contrato-sinergis-1.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/contrato-sinergis-1.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 2116839,
    providerIdentity: "SINERGIS, S.A. DE C.V.",
    area: "Digital",
    contractObject: "Marketing, publicidad y administración de plataforma Beyond.",
    communicationType: "remision",
    relationType: "encargado",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "Vigésima Segunda. Protección de Datos Personales",
    analysisSummary: "La cláusula no cumple con los requisitos revisados.",
    recommendation: "Usar cláusula C1 o apéndice CM-1.",
    riskLevel: "medio",
    documentKind: "Contrato firmado",
  },
  {
    id: "grunenthal-grt-contract-026-corad-2020",
    slug: "corad-2020",
    sourceName: "CORAD 2020.pdf",
    fileName: "corad-2020.pdf",
    displayName: "CORAD 2020",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/corad-2020.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/corad-2020.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 1990610,
    providerIdentity: "CORAD MEETING PLANNER, S.A. DE C.V.",
    area: "Compras",
    contractObject: "Operación de grupos, congresos, convenciones, transportación, producción y viajes.",
    communicationType: "transferencia",
    relationType: "tercero",
    clauseComplianceStatus: "no_aplica",
    clauseComplianceLabel: "Agregar cláusula",
    clauseType: "No se encontró cláusula relativa.",
    analysisSummary: "El análisis fuente no localizó cláusula relativa y requiere agregar la cláusula aplicable.",
    recommendation: "Incorporar cláusula C2 o apéndice CM-2.",
    riskLevel: "medio",
    documentKind: "Contrato firmado",
  },
  {
    id: "grunenthal-grt-contract-027-cps-knobloch-v2-final-04-04-signed-1",
    slug: "cps-knobloch-v2-final-04-04-signed-1",
    sourceName: "CPS_KNobloch_V2_ final (04.04) - signed (1).pdf",
    fileName: "cps-knobloch-v2-final-04-04-signed-1.pdf",
    displayName: "CPS_KNobloch_V2_ final (04.04) - signed (1)",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/cps-knobloch-v2-final-04-04-signed-1.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/cps-knobloch-v2-final-04-04-signed-1.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 1761467,
    providerIdentity: "CID CENTRO INTEGRADOR DE DATOS, S.A. DE C.V. (Knobloch)",
    area: "COMEX",
    contractObject: "Entrega de base de datos electrónica.",
    communicationType: "transferencia",
    relationType: "tercero",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "Vigésima Primera. Protección de Datos Personales",
    analysisSummary: "La cláusula no cumple con los requisitos de la LFPDPPP.",
    recommendation: "Usar cláusula C2 o apéndice CM-2.",
    riskLevel: "medio",
    documentKind: "Contrato firmado",
  },
  {
    id: "grunenthal-grt-contract-028-cpsespecializados-inefam-11-04-v2-cl-signed",
    slug: "cpsespecializados-inefam-11-04-v2-cl-signed",
    sourceName: "CPSEspecializados_INEFAM (11.04)_V2_cl - signed.pdf",
    fileName: "cpsespecializados-inefam-11-04-v2-cl-signed.pdf",
    displayName: "CPSEspecializados_INEFAM (11.04)_V2_cl - signed",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/cpsespecializados-inefam-11-04-v2-cl-signed.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/cpsespecializados-inefam-11-04-v2-cl-signed.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 2481490,
    providerIdentity: "INSTITUTO DE INVESTIGACIÓN E INNOVACIÓN FARMACÉUTICA, A.C. (INEFAM)",
    area: "COMEX",
    contractObject: "Suscripción y entrega de reportes por parte de INEFAM.",
    communicationType: "transferencia",
    relationType: "tercero",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "Vigésima. Protección de Datos Personales",
    analysisSummary: "La cláusula no cumple con los requisitos de la LFPDPPP.",
    recommendation: "Usar cláusula C2 o apéndice CM-2.",
    riskLevel: "medio",
    documentKind: "Contrato firmado",
  },
  {
    id: "grunenthal-grt-contract-029-d-ms-drugs",
    slug: "d-ms-drugs",
    sourceName: "D&MS Drugs .pdf",
    fileName: "d-ms-drugs.pdf",
    displayName: "D&MS Drugs ",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/d-ms-drugs.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/d-ms-drugs.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 2491416,
    providerIdentity: "D&MS DRUGS AND MARKETSHARE, S.C.",
    area: "COMEX",
    contractObject: "Generación de sistema de incentivos.",
    communicationType: "sin-comunicacion",
    relationType: "sin-comunicacion",
    clauseComplianceStatus: "cumple",
    clauseComplianceLabel: "Sí cumple",
    clauseType: "Vigésima. Protección de Datos Personales",
    analysisSummary: "La cláusula cumple con los requisitos del análisis fuente.",
    recommendation: "Mantener evidencia y revisión anual.",
    riskLevel: "bajo",
    documentKind: "Contrato firmado",
  },
  {
    id: "grunenthal-grt-contract-030-dpa-concur",
    slug: "dpa-concur",
    sourceName: "DPA CONCUR.pdf",
    fileName: "dpa-concur.pdf",
    displayName: "DPA CONCUR",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/dpa-concur.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/dpa-concur.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 413835,
    providerIdentity: "CONCUR TECHNOLOGIES, INC.",
    area: "Globales",
    contractObject: "Servicios de nube.",
    communicationType: "remision",
    relationType: "encargado",
    clauseComplianceStatus: "cumple",
    clauseComplianceLabel: "Sí cumple",
    clauseType: "Data Processing Agreement",
    analysisSummary: "El análisis fuente marca cumplimiento para el DPA.",
    recommendation: "Mantener evidencia y revisión anual.",
    riskLevel: "bajo",
    documentKind: "DPA",
  },
  {
    id: "grunenthal-grt-contract-031-eve230601-sow-global-mi-operational-signed-2",
    slug: "eve230601-sow-global-mi-operational-signed-2",
    sourceName: "EVE230601 SOW Global MI Operational - signed (2).pdf",
    fileName: "eve230601-sow-global-mi-operational-signed-2.pdf",
    displayName: "EVE230601 SOW Global MI Operational - signed (2)",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/eve230601-sow-global-mi-operational-signed-2.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/eve230601-sow-global-mi-operational-signed-2.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 905258,
    providerIdentity: "EVERSANA, IRELAND, LIMITED",
    area: "Globales",
    contractObject: "Servicios vinculados al acuerdo de protección de datos.",
    communicationType: "remision",
    relationType: "encargado",
    clauseComplianceStatus: "cumple",
    clauseComplianceLabel: "Sí cumple",
    clauseType: "SOW / DPA asociado",
    analysisSummary: "El análisis fuente marca cumplimiento para EVERSANA.",
    recommendation: "Mantener SOW vinculado al DPA vigente.",
    riskLevel: "bajo",
    documentKind: "SOW firmado",
  },
  {
    id: "grunenthal-grt-contract-032-grunenthal-contrato-determinado-plantilla-jdv-cambios",
    slug: "grunenthal-contrato-determinado-plantilla-jdv-cambios",
    sourceName: "Grunenthal - CONTRATO DETERMINADO PLANTILLA (JDV cambios).docx",
    fileName: "grunenthal-contrato-determinado-plantilla-jdv-cambios.docx",
    displayName: "Grunenthal - CONTRATO DETERMINADO PLANTILLA (JDV cambios)",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/grunenthal-contrato-determinado-plantilla-jdv-cambios.docx",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/grunenthal-contrato-determinado-plantilla-jdv-cambios-preview.pdf",
    extension: "docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: 56793,
    providerIdentity: "Plantilla laboral Grünenthal - tiempo determinado",
    area: "Human Resources",
    contractObject: "Plantilla de contrato individual por tiempo determinado.",
    communicationType: "sin-comunicacion",
    relationType: "sin-comunicacion",
    clauseComplianceStatus: "no_aplica",
    clauseComplianceLabel: "N/A",
    clauseType: "Plantilla laboral C4",
    analysisSummary: "No es contrato con tercero operativo; se conserva como referencia documental en terceros por venir en la carpeta fuente.",
    recommendation: "Usar como plantilla, no como evidencia de proveedor.",
    riskLevel: "bajo",
    documentKind: "Plantilla DOCX",
  },
  {
    id: "grunenthal-grt-contract-033-grunenthal-contrato-indeterminado-plantilla-jdv-cambios",
    slug: "grunenthal-contrato-indeterminado-plantilla-jdv-cambios",
    sourceName: "Grunenthal - CONTRATO INDETERMINADO PLANTILLA (JDV cambios).docx",
    fileName: "grunenthal-contrato-indeterminado-plantilla-jdv-cambios.docx",
    displayName: "Grunenthal - CONTRATO INDETERMINADO PLANTILLA (JDV cambios)",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/grunenthal-contrato-indeterminado-plantilla-jdv-cambios.docx",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/grunenthal-contrato-indeterminado-plantilla-jdv-cambios-preview.pdf",
    extension: "docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: 57845,
    providerIdentity: "Plantilla laboral Grünenthal - tiempo indeterminado",
    area: "Human Resources",
    contractObject: "Plantilla de contrato individual por tiempo indeterminado.",
    communicationType: "sin-comunicacion",
    relationType: "sin-comunicacion",
    clauseComplianceStatus: "no_aplica",
    clauseComplianceLabel: "N/A",
    clauseType: "Plantilla laboral C4",
    analysisSummary: "No es contrato con tercero operativo; se conserva como referencia documental en terceros por venir en la carpeta fuente.",
    recommendation: "Usar como plantilla, no como evidencia de proveedor.",
    riskLevel: "bajo",
    documentKind: "Plantilla DOCX",
  },
  {
    id: "grunenthal-grt-contract-034-leaseplan",
    slug: "leaseplan",
    sourceName: "Leaseplan.pdf",
    fileName: "leaseplan.pdf",
    displayName: "Leaseplan",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/leaseplan.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/leaseplan.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 1031924,
    providerIdentity: "LEASEPLAN DE MÉXICO, S.A. DE C.V.",
    area: "Flotilla",
    contractObject: "Arrendamiento puro y servicios de gestión de flota.",
    communicationType: "mixta",
    relationType: "mixta",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "No se encontró cláusula relativa.",
    analysisSummary: "El análisis fuente sugiere falta de cláusula o instrumento suficiente.",
    recommendation: "Usar C1/CM-1 para gestión de flota y C2/CM-2 para derecho de adquisición.",
    riskLevel: "alto",
    documentKind: "Contrato firmado",
  },
  {
    id: "grunenthal-grt-contract-035-microsoftonlineservicesterms-german-october2016-cr",
    slug: "microsoftonlineservicesterms-german-october2016-cr",
    sourceName: "MicrosoftOnlineServicesTerms(German)(October2016)(cr).pdf",
    fileName: "microsoftonlineservicesterms-german-october2016-cr.pdf",
    displayName: "MicrosoftOnlineServicesTerms(German)(October2016)(cr)",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/microsoftonlineservicesterms-german-october2016-cr.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/microsoftonlineservicesterms-german-october2016-cr.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 647409,
    providerIdentity: "MICROSOFT CORPORATION",
    area: "Globales",
    contractObject: "Licencia para uso de software y servicios en línea.",
    communicationType: "remision",
    relationType: "encargado",
    clauseComplianceStatus: "cumple",
    clauseComplianceLabel: "Sí cumple",
    clauseType: "Online Services Terms",
    analysisSummary: "El análisis fuente marca cumplimiento para servicios Microsoft.",
    recommendation: "Mantener términos y DPA vigentes.",
    riskLevel: "bajo",
    documentKind: "Términos de servicio",
  },
  {
    id: "grunenthal-grt-contract-036-oro-agreement-for-grunenthal-7-23-23-final-signed",
    slug: "oro-agreement-for-grunenthal-7-23-23-final-signed",
    sourceName: "ORO Agreement_for_Grunenthal_7-23-23_Final - signed.pdf",
    fileName: "oro-agreement-for-grunenthal-7-23-23-final-signed.pdf",
    displayName: "ORO Agreement_for_Grunenthal_7-23-23_Final - signed",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/oro-agreement-for-grunenthal-7-23-23-final-signed.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/oro-agreement-for-grunenthal-7-23-23-final-signed.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 1757901,
    providerIdentity: "ORO LABS, INC.",
    area: "Compras",
    contractObject: "Convenio de nube.",
    communicationType: "remision",
    relationType: "encargado",
    clauseComplianceStatus: "cumple",
    clauseComplianceLabel: "Sí cumple",
    clauseType: "Standard Contractual Clauses Controller to Processor",
    analysisSummary: "La cláusula cumple con los requisitos del análisis fuente.",
    recommendation: "Mantener evidencia y revisión anual.",
    riskLevel: "bajo",
    documentKind: "Contrato firmado",
  },
  {
    id: "grunenthal-grt-contract-037-renewal-jan-2025-gruunenthal-latam-regional-opendata",
    slug: "renewal-jan-2025-gruunenthal-latam-regional-opendata",
    sourceName: "Renewal Jan 2025- Gruunenthal LatAm Regional OpenData.pdf",
    fileName: "renewal-jan-2025-gruunenthal-latam-regional-opendata.pdf",
    displayName: "Renewal Jan 2025- Gruunenthal LatAm Regional OpenData",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/renewal-jan-2025-gruunenthal-latam-regional-opendata.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/renewal-jan-2025-gruunenthal-latam-regional-opendata.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 177695,
    providerIdentity: "VEEVA SYSTEMS INC.",
    area: "COMEX",
    contractObject: "Orden de renovación OpenData regional LatAm.",
    communicationType: "transferencia",
    relationType: "tercero",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "Addendum to MSA / MyVeeva",
    analysisSummary: "La cláusula no cumple con los requisitos de la LFPDPPP conforme al análisis fuente.",
    recommendation: "Usar cláusula C2 o apéndice CM-2.",
    riskLevel: "medio",
    documentKind: "Orden de renovación",
  },
  {
    id: "grunenthal-grt-contract-038-salesforce-dpa-signed",
    slug: "salesforce-dpa-signed",
    sourceName: "Salesforce-DPA - signed.pdf",
    fileName: "salesforce-dpa-signed.pdf",
    displayName: "Salesforce-DPA - signed",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/salesforce-dpa-signed.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/salesforce-dpa-signed.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 993316,
    providerIdentity: "SALESFORCE, INC.",
    area: "Globales",
    contractObject: "Servicios de software.",
    communicationType: "remision",
    relationType: "encargado",
    clauseComplianceStatus: "cumple",
    clauseComplianceLabel: "Sí cumple",
    clauseType: "Data Processing Agreement",
    analysisSummary: "El análisis fuente marca cumplimiento para Salesforce.",
    recommendation: "Mantener DPA firmado y revisión anual.",
    riskLevel: "bajo",
    documentKind: "DPA firmado",
  },
  {
    id: "grunenthal-grt-contract-039-sap-cloud-services-data-processing-agreement-for-cloud-services",
    slug: "sap-cloud-services-data-processing-agreement-for-cloud-services",
    sourceName: "SAP Cloud Services Data+Processing+Agreement+for+Cloud+Services.pdf",
    fileName: "sap-cloud-services-data-processing-agreement-for-cloud-services.pdf",
    displayName: "SAP Cloud Services Data+Processing+Agreement+for+Cloud+Services",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/sap-cloud-services-data-processing-agreement-for-cloud-services.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/sap-cloud-services-data-processing-agreement-for-cloud-services.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 187342,
    providerIdentity: "SAP SE",
    area: "Globales",
    contractObject: "Servicios de nube.",
    communicationType: "remision",
    relationType: "encargado",
    clauseComplianceStatus: "cumple",
    clauseComplianceLabel: "Sí cumple",
    clauseType: "Data Processing Agreement for Cloud Services",
    analysisSummary: "El análisis fuente marca cumplimiento para SAP.",
    recommendation: "Mantener DPA vigente y revisión anual.",
    riskLevel: "bajo",
    documentKind: "DPA",
  },
  {
    id: "grunenthal-grt-contract-040-sivale",
    slug: "sivale",
    sourceName: "SíVale.pdf",
    fileName: "sivale.pdf",
    displayName: "SíVale",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/sivale.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/sivale.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 281140,
    providerIdentity: "SÍ VALE MÉXICO, S.A. DE C.V.",
    area: "Human Resources",
    contractObject: "Emisión y gestión de monederos para trabajadores.",
    communicationType: "transferencia",
    relationType: "tercero",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "Cláusula de protección de datos revisada en análisis fuente.",
    analysisSummary: "La transferencia requiere reforzar instrumento contractual.",
    recommendation: "Usar cláusula C2 o apéndice CM-2.",
    riskLevel: "medio",
    documentKind: "Contrato firmado",
  },
  {
    id: "grunenthal-grt-contract-041-terminos-de-servicio-de-vimeo",
    slug: "terminos-de-servicio-de-vimeo",
    sourceName: "Términos de servicio de Vimeo.pdf",
    fileName: "terminos-de-servicio-de-vimeo.pdf",
    displayName: "Términos de servicio de Vimeo",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/terminos-de-servicio-de-vimeo.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/terminos-de-servicio-de-vimeo.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 489020,
    providerIdentity: "VIMEO",
    area: "Globales",
    contractObject: "Términos de Uso de plataforma para la creación y divulgación de videos.",
    communicationType: "transferencia",
    relationType: "tercero",
    clauseComplianceStatus: "cumple",
    clauseComplianceLabel: "Sí cumple",
    clauseType: "(1) Privacy policy",
    analysisSummary: "La cláusula si cumplen con los requisitos de la LFPDPPP.",
    recommendation: "La cláusula si cumplen con los requisitos de la LFPDPPP.",
    riskLevel: "bajo",
    documentKind: "Términos de uso",
  },
  {
    id: "grunenthal-grt-contract-042-gptw-grunenthal-av-vertrag",
    slug: "gptw-grunenthal-av-vertrag",
    sourceName: "GPTW_Grünenthal_AV-Vertrag (1).pdf",
    fileName: "gptw-grunenthal-av-vertrag.pdf",
    displayName: "GPTW Grünenthal AV-Vertrag",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/gptw-grunenthal-av-vertrag.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/gptw-grunenthal-av-vertrag.pdf",
    extension: "pdf",
    mimeType: "application/pdf",
    size: 10889968,
    providerIdentity: "GPTW Deutschland GmbH",
    area: "Globales",
    contractObject: "Servicios para la certificación como Great Place To Work.",
    communicationType: "transferencia",
    relationType: "tercero",
    clauseComplianceStatus: "no_cumple",
    clauseComplianceLabel: "No cumple",
    clauseType: "(1) Auftragsverarbeitungsvertrag",
    analysisSummary:
      "El contrato regula una remisión de datos personales, como el responsable trata los datos personales de manera independiente de Grünenthal, con el objetivo de funcionar como un certificador independiente, se debe de considerar una transferencia.",
    recommendation:
      "El contrato regula una remisión de datos personales, como el responsable trata los datos personales de manera independiente de Grünenthal, con el objetivo de funcionar como un certificador independiente, se debe de considerar una transferencia.",
    riskLevel: "medio",
    documentKind: "Contrato de servicios",
  },
  {
    id: "grunenthal-grt-contract-043-contract-mastercontrol",
    slug: "contract-mastercontrol",
    sourceName: "Contract+MasterControl.pdf",
    fileName: "contract-mastercontrol.pdf",
    displayName: "Contract MasterControl",
    path: "/client/grunenthal/third-party-contracts/contratos-grt/contract-mastercontrol.pdf",
    previewPdfPath: "/client/grunenthal/third-party-contracts/contratos-grt/contract-mastercontrol.pdf",
    previewPageImagePaths: MASTER_CONTROL_PREVIEW_IMAGE_PATHS,
    extension: "pdf",
    mimeType: "application/pdf",
    size: 8814242,
    providerIdentity: "MASTER CONTROL INC.",
    area: "Globales",
    contractObject: "Licencia de uso de software y prestación de servicios de capacitación.",
    communicationType: "remision",
    relationType: "encargado",
    clauseComplianceStatus: "cumple",
    clauseComplianceLabel: "Sí cumple",
    clauseType: "(1) Data Processing Addendum",
    analysisSummary: "La cláusula si cumplen con los requisitos de la LFPDPPP.",
    recommendation: "La cláusula si cumplen con los requisitos de la LFPDPPP.",
    riskLevel: "bajo",
    documentKind: "Contrato de licencia",
  },
]
