// Generated from Políticas de Grünenthal (2026). Keep edits in the generator/source set.

export const GRUNENTHAL_CLIENT_NAME = "Grünenthal"
export const GRUNENTHAL_ASSET_BASE_PATH = "/client/grunenthal"

export type GrunenthalAssetModule =
  | "arco-rights"
  | "brand"
  | "data-policies"
  | "davara-training"
  | "dpo"
  | "general-library"
  | "privacy-notices"
  | "rat"
  | "security-system"
  | "third-party-contracts"

export interface GrunenthalAsset {
  id: string
  name: string
  displayName: string
  path: string
  type: string
  size: number
  module: GrunenthalAssetModule
  category: string
  folder: string
  extension: string
  sourceRelativePath: string
  ratAreaFolder?: string
  ratPdfTitle?: string
}

export const GRUNENTHAL_LOGO = {
  path: "/client/grunenthal/brand/grunenthal-logo-green.png",
  whiteFilter: "brightness(0) invert(1)",
  blackFilter: "brightness(0)",
} as const

export const GRUNENTHAL_DOCUMENT_MANIFEST: GrunenthalAsset[] = [
  {
    "id": "grunenthal-brand-grunenthal-logo-green",
    "name": "Grünenthal_logo_green.png",
    "displayName": "Grünenthal_logo_green",
    "path": "/client/grunenthal/brand/grunenthal-logo-green.png",
    "type": "image/png",
    "size": 42242,
    "module": "brand",
    "category": "brand",
    "folder": "brand",
    "extension": "png",
    "sourceRelativePath": "Grünenthal_logo_green.png"
  },
  {
    "id": "grunenthal-rat-inventario-comex-comunicacion-opioddisclaimer-hcps-davara",
    "name": "inventario_COMEX_-_Comunicación_OpiodDisclaimer_HCPs_ davara .pdf",
    "displayName": "inventario_COMEX_-_Comunicación_OpiodDisclaimer_HCPs_ davara ",
    "path": "/client/grunenthal/rat/comex/inventario-comex-comunicacion-opioddisclaimer-hcps-davara.pdf",
    "type": "application/pdf",
    "size": 110933,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/comex",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/COMEX/inventario_COMEX_-_Comunicación_OpiodDisclaimer_HCPs_ davara .pdf",
    "ratAreaFolder": "COMEX",
    "ratPdfTitle": "COMEX - Comunicacion OpiodDisclaimer HCPs"
  },
  {
    "id": "grunenthal-rat-inventario-comex-ranking-de-efectividad",
    "name": "inventario_COMEX_-_Ranking_de_efectividad.pdf",
    "displayName": "inventario_COMEX_-_Ranking_de_efectividad",
    "path": "/client/grunenthal/rat/comex/inventario-comex-ranking-de-efectividad.pdf",
    "type": "application/pdf",
    "size": 97496,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/comex",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/COMEX/inventario_COMEX_-_Ranking_de_efectividad.pdf",
    "ratAreaFolder": "COMEX",
    "ratPdfTitle": "COMEX - Ranking de efectividad"
  },
  {
    "id": "grunenthal-rat-inventario-comex-directorio-de-ventas",
    "name": "inventario_Comex_-_Directorio_de_Ventas.pdf",
    "displayName": "inventario_Comex_-_Directorio_de_Ventas",
    "path": "/client/grunenthal/rat/comex/inventario-comex-directorio-de-ventas.pdf",
    "type": "application/pdf",
    "size": 119102,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/comex",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/COMEX/inventario_Comex_-_Directorio_de_Ventas.pdf",
    "ratAreaFolder": "COMEX",
    "ratPdfTitle": "Comex - Directorio de Ventas"
  },
  {
    "id": "grunenthal-rat-inventario-compras-base-de-datos-de-titulares-sin-tarjeta-corporativa",
    "name": "inventario_Compras_-_Base_de_datos_de_titulares_sin_tarjeta_corporativa.pdf",
    "displayName": "inventario_Compras_-_Base_de_datos_de_titulares_sin_tarjeta_corporativa",
    "path": "/client/grunenthal/rat/compras/inventario-compras-base-de-datos-de-titulares-sin-tarjeta-corporativa.pdf",
    "type": "application/pdf",
    "size": 119049,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/compras",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Compras/inventario_Compras_-_Base_de_datos_de_titulares_sin_tarjeta_corporativa.pdf",
    "ratAreaFolder": "Compras",
    "ratPdfTitle": "Compras - Base de datos de titulares sin tarjeta corporativa"
  },
  {
    "id": "grunenthal-rat-inventario-compras-concur",
    "name": "inventario_Compras_-_Concur.pdf",
    "displayName": "inventario_Compras_-_Concur",
    "path": "/client/grunenthal/rat/compras/inventario-compras-concur.pdf",
    "type": "application/pdf",
    "size": 187903,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/compras",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Compras/inventario_Compras_-_Concur.pdf",
    "ratAreaFolder": "Compras",
    "ratPdfTitle": "Compras - Concur"
  },
  {
    "id": "grunenthal-rat-inventario-compras-sistema-oro",
    "name": "inventario_Compras_-_Sistema_Oro.pdf",
    "displayName": "inventario_Compras_-_Sistema_Oro",
    "path": "/client/grunenthal/rat/compras/inventario-compras-sistema-oro.pdf",
    "type": "application/pdf",
    "size": 134015,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/compras",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Compras/inventario_Compras_-_Sistema_Oro.pdf",
    "ratAreaFolder": "Compras",
    "ratPdfTitle": "Compras - Sistema Oro"
  },
  {
    "id": "grunenthal-rat-inventario-digital-registro-beyond",
    "name": "inventario_Digital_-_Registro_Beyond.pdf",
    "displayName": "inventario_Digital_-_Registro_Beyond",
    "path": "/client/grunenthal/rat/digital/inventario-digital-registro-beyond.pdf",
    "type": "application/pdf",
    "size": 115667,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/digital",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Digital/inventario_Digital_-_Registro_Beyond.pdf",
    "ratAreaFolder": "Digital",
    "ratPdfTitle": "Digital - Registro Beyond"
  },
  {
    "id": "grunenthal-rat-inventario-digital-salesforce-marketing-davara",
    "name": "inventario_Digital_-_Salesforce_Marketing davara .pdf",
    "displayName": "inventario_Digital_-_Salesforce_Marketing davara ",
    "path": "/client/grunenthal/rat/digital/inventario-digital-salesforce-marketing-davara.pdf",
    "type": "application/pdf",
    "size": 112370,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/digital",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Digital/inventario_Digital_-_Salesforce_Marketing davara .pdf",
    "ratAreaFolder": "Digital",
    "ratPdfTitle": "Digital - Salesforce Marketing"
  },
  {
    "id": "grunenthal-rat-inventario-direccion-general-conave-mexico",
    "name": "inventario_Dirección_General_-_Conave_México.pdf",
    "displayName": "inventario_Dirección_General_-_Conave_México",
    "path": "/client/grunenthal/rat/direccion-general/inventario-direccion-general-conave-mexico.pdf",
    "type": "application/pdf",
    "size": 132481,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/direccion-general",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Dirección General/inventario_Dirección_General_-_Conave_México.pdf",
    "ratAreaFolder": "Dirección General",
    "ratPdfTitle": "Direccion General - Conave Mexico"
  },
  {
    "id": "grunenthal-rat-inventario-direccion-general-listado-de-tallas-core-team",
    "name": "inventario_Dirección_General_-_Listado_de_Tallas_Core_Team.pdf",
    "displayName": "inventario_Dirección_General_-_Listado_de_Tallas_Core_Team",
    "path": "/client/grunenthal/rat/direccion-general/inventario-direccion-general-listado-de-tallas-core-team.pdf",
    "type": "application/pdf",
    "size": 116525,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/direccion-general",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Dirección General/inventario_Dirección_General_-_Listado_de_Tallas_Core_Team.pdf",
    "ratAreaFolder": "Dirección General",
    "ratPdfTitle": "Direccion General - Listado de Tallas Core Team"
  },
  {
    "id": "grunenthal-rat-inventario-direccion-general-rooming-general",
    "name": "inventario_Dirección_General_-_Rooming_General.pdf",
    "displayName": "inventario_Dirección_General_-_Rooming_General",
    "path": "/client/grunenthal/rat/direccion-general/inventario-direccion-general-rooming-general.pdf",
    "type": "application/pdf",
    "size": 120546,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/direccion-general",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Dirección General/inventario_Dirección_General_-_Rooming_General.pdf",
    "ratAreaFolder": "Dirección General",
    "ratPdfTitle": "Direccion General - Rooming General"
  },
  {
    "id": "grunenthal-rat-inventario-dolor-listado-de-medicos-ametd",
    "name": "inventario_Dolor_-_Listado_de_Médicos_AMETD.pdf",
    "displayName": "inventario_Dolor_-_Listado_de_Médicos_AMETD",
    "path": "/client/grunenthal/rat/dolor/inventario-dolor-listado-de-medicos-ametd.pdf",
    "type": "application/pdf",
    "size": 118676,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/dolor",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Dolor/inventario_Dolor_-_Listado_de_Médicos_AMETD.pdf",
    "ratAreaFolder": "Dolor",
    "ratPdfTitle": "Dolor - Listado de Medicos AMETD"
  },
  {
    "id": "grunenthal-rat-inventario-dolor-perfil-de-medico-salesforce",
    "name": "inventario_Dolor_-_Perfil_de_Médico_Salesforce_.pdf",
    "displayName": "inventario_Dolor_-_Perfil_de_Médico_Salesforce_",
    "path": "/client/grunenthal/rat/dolor/inventario-dolor-perfil-de-medico-salesforce.pdf",
    "type": "application/pdf",
    "size": 170630,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/dolor",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Dolor/inventario_Dolor_-_Perfil_de_Médico_Salesforce_.pdf",
    "ratAreaFolder": "Dolor",
    "ratPdfTitle": "Dolor - Perfil de Medico Salesforce"
  },
  {
    "id": "grunenthal-rat-inventario-entrenamiento-master-evaluaciones",
    "name": "inventario_Entrenamiento_-_Master_Evaluaciones.pdf",
    "displayName": "inventario_Entrenamiento_-_Master_Evaluaciones",
    "path": "/client/grunenthal/rat/entrenamiento/inventario-entrenamiento-master-evaluaciones.pdf",
    "type": "application/pdf",
    "size": 120628,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/entrenamiento",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Entrenamiento/inventario_Entrenamiento_-_Master_Evaluaciones.pdf",
    "ratAreaFolder": "Entrenamiento",
    "ratPdfTitle": "Entrenamiento - Master Evaluaciones"
  },
  {
    "id": "grunenthal-rat-inventario-flotilla-carta-responsiva-de-automovil",
    "name": "inventario_Flotilla_-_Carta_Responsiva_de_Automóvil.pdf",
    "displayName": "inventario_Flotilla_-_Carta_Responsiva_de_Automóvil",
    "path": "/client/grunenthal/rat/flotilla/inventario-flotilla-carta-responsiva-de-automovil.pdf",
    "type": "application/pdf",
    "size": 121838,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/flotilla",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Flotilla/inventario_Flotilla_-_Carta_Responsiva_de_Automóvil.pdf",
    "ratAreaFolder": "Flotilla",
    "ratPdfTitle": "Flotilla - Carta Responsiva de Automovil"
  },
  {
    "id": "grunenthal-rat-inventario-flotilla-informacion-solicitada-a-empleado-por-correo",
    "name": "inventario-flotilla-compraventa-vehiculo-empleados.pdf",
    "displayName": "inventario-flotilla-compraventa-vehiculo-empleados",
    "path": "/client/grunenthal/rat/flotilla/inventario-flotilla-informacion-solicitada-a-empleado-por-correo.pdf",
    "type": "application/pdf",
    "size": 120739,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/flotilla",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Flotilla/inventario_Flotilla_-_Información_solicitada_a_empleado_por_Correo.pdf",
    "ratAreaFolder": "Flotilla",
    "ratPdfTitle": "Flotilla - Compraventa-vehículo empleados"
  },
  {
    "id": "grunenthal-rat-inventario-flotilla-solicitud-de-fondo-de-garantia-de-auto",
    "name": "inventario_Flotilla_-_Solicitud_de_Fondo_de_Garantía_de_Auto_.pdf",
    "displayName": "inventario_Flotilla_-_Solicitud_de_Fondo_de_Garantía_de_Auto_",
    "path": "/client/grunenthal/rat/flotilla/inventario-flotilla-solicitud-de-fondo-de-garantia-de-auto.pdf",
    "type": "application/pdf",
    "size": 117218,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/flotilla",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Flotilla/inventario_Flotilla_-_Solicitud_de_Fondo_de_Garantía_de_Auto_.pdf",
    "ratAreaFolder": "Flotilla",
    "ratPdfTitle": "Flotilla - Solicitud de Fondo de Garantia de Auto"
  },
  {
    "id": "grunenthal-rat-inventario-human-resources-bacher-zoppi-catalogo-de-empleados",
    "name": "inventario_Human_Resources_-_Bacher_Zoppi_(Catálogo_de_Empleados)_.pdf",
    "displayName": "inventario_Human_Resources_-_Bacher_Zoppi_(Catálogo_de_Empleados)_",
    "path": "/client/grunenthal/rat/hr/inventario-human-resources-bacher-zoppi-catalogo-de-empleados.pdf",
    "type": "application/pdf",
    "size": 112214,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/hr",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/HR/inventario_Human_Resources_-_Bacher_Zoppi_(Catálogo_de_Empleados)_.pdf",
    "ratAreaFolder": "HR",
    "ratPdfTitle": "Human Resources - Bacher Zoppi Catalogo de Empleados"
  },
  {
    "id": "grunenthal-rat-inventario-human-resources-formato-de-alta-proveedor",
    "name": "inventario-human-resources-empleados-de-proveedores.pdf",
    "displayName": "inventario-human-resources-empleados-de-proveedores",
    "path": "/client/grunenthal/rat/hr/inventario-human-resources-formato-de-alta-proveedor.pdf",
    "type": "application/pdf",
    "size": 135365,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/hr",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/HR/inventario_Human_Resources_-_Formato_de_alta_proveedor.pdf",
    "ratAreaFolder": "HR",
    "ratPdfTitle": "Human Resources - Empleados de proveedores"
  },
  {
    "id": "grunenthal-rat-inventario-human-resources-cedula-de-datos",
    "name": "inventario-human-resources-myview.pdf",
    "displayName": "inventario-human-resources-myview",
    "path": "/client/grunenthal/rat/hr/inventario-human-resources-cedula-de-datos.pdf",
    "type": "application/pdf",
    "size": 203689,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/hr",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/HR/inventario_Human_resources_-_Cédula_de_Datos.pdf",
    "ratAreaFolder": "HR",
    "ratPdfTitle": "Human resources - MyView"
  },
  {
    "id": "grunenthal-rat-inventario-human-resources-checklist-de-documentacion",
    "name": "inventario-human-resources-checklist-documentacion-de-nuevos-empleados.pdf",
    "displayName": "inventario-human-resources-checklist-documentacion-de-nuevos-empleados",
    "path": "/client/grunenthal/rat/hr/inventario-human-resources-checklist-de-documentacion.pdf",
    "type": "application/pdf",
    "size": 138781,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/hr",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/HR/inventario_Human_resources_-_Checklist_de_documentación.pdf",
    "ratAreaFolder": "HR",
    "ratPdfTitle": "Human resources - Checklist documentación de nuevos empleados"
  },
  {
    "id": "grunenthal-rat-inventario-it-sistema-azure-1",
    "name": "inventario_IT_-_Sistema_Azure (1).pdf",
    "displayName": "inventario_IT_-_Sistema_Azure (1)",
    "path": "/client/grunenthal/rat/it/inventario-it-sistema-azure-1.pdf",
    "type": "application/pdf",
    "size": 143519,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/it",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/IT/inventario_IT_-_Sistema_Azure (1).pdf",
    "ratAreaFolder": "IT",
    "ratPdfTitle": "IT - Sistema Azure 1"
  },
  {
    "id": "grunenthal-rat-inventario-investigacion-de-mercados-sinefarma",
    "name": "inventario_Investigación_de_Mercados_-_Sinefarma.pdf",
    "displayName": "inventario_Investigación_de_Mercados_-_Sinefarma",
    "path": "/client/grunenthal/rat/investigacion-de-mercado/inventario-investigacion-de-mercados-sinefarma.pdf",
    "type": "application/pdf",
    "size": 112341,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/investigacion-de-mercado",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Investigación De Mercado/inventario_Investigación_de_Mercados_-_Sinefarma.pdf",
    "ratAreaFolder": "Investigación De Mercado",
    "ratPdfTitle": "Investigacion de Mercados - Sinefarma"
  },
  {
    "id": "grunenthal-rat-inventario-medical-information-base-de-datos-de-tracker-y-correos-electronicos-1",
    "name": "inventario_Medical_Information_-_Base_de_datos_de_Tracker_y_Correos_Electrónicos (1).pdf",
    "displayName": "inventario_Medical_Information_-_Base_de_datos_de_Tracker_y_Correos_Electrónicos (1)",
    "path": "/client/grunenthal/rat/medical-information/inventario-medical-information-base-de-datos-de-tracker-y-correos-electronicos-1.pdf",
    "type": "application/pdf",
    "size": 130338,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/medical-information",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Medical information/inventario_Medical_Information_-_Base_de_datos_de_Tracker_y_Correos_Electrónicos (1).pdf",
    "ratAreaFolder": "Medical information",
    "ratPdfTitle": "Medical Information - Base de datos de Tracker y Correos Electronicos 1"
  },
  {
    "id": "grunenthal-rat-inventario-medical-lista-de-requerimientos-hcp-profesional-de-salud-nacional",
    "name": "inventario-medical-lista-de-requerimientos-contratacion-hcp-profesional-de-salud-nacional.pdf",
    "displayName": "inventario-medical-lista-de-requerimientos-contratacion-hcp-profesional-de-salud-nacional",
    "path": "/client/grunenthal/rat/medical/inventario-medical-lista-de-requerimientos-hcp-profesional-de-salud-nacional.pdf",
    "type": "application/pdf",
    "size": 120680,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/medical",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Medical/inventario_Medical_-_Lista_de_requerimientos_HCP_(Profesional_de_salud_nacional)_.pdf",
    "ratAreaFolder": "Medical",
    "ratPdfTitle": "Medical - Lista de requerimientos contratación HCP (Profesional de salud nacional)"
  },
  {
    "id": "grunenthal-rat-inventario-medical-lista-de-requerimientos-hcp-profesionales-de-la-salud-extranjero",
    "name": "inventario-medical-lista-de-requerimientos-contratacion-hcp-profesionales-de-la-salud-extranjero.pdf",
    "displayName": "inventario-medical-lista-de-requerimientos-contratacion-hcp-profesionales-de-la-salud-extranjero",
    "path": "/client/grunenthal/rat/medical/inventario-medical-lista-de-requerimientos-hcp-profesionales-de-la-salud-extranjero.pdf",
    "type": "application/pdf",
    "size": 117133,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/medical",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Medical/inventario_Medical_-_Lista_de_requerimientos_HCP_(Profesionales_de_la_salud_extranjero).pdf",
    "ratAreaFolder": "Medical",
    "ratPdfTitle": "Medical - Lista de requerimientos contratación HCP (Profesionales de la salud extranjero)"
  },
  {
    "id": "grunenthal-rat-inventario-medical-lista-de-requerimientos-donaciones",
    "name": "inventario_Medical_lista_de_requerimientos_donaciones.pdf",
    "displayName": "inventario_Medical_lista_de_requerimientos_donaciones",
    "path": "/client/grunenthal/rat/medical/inventario-medical-lista-de-requerimientos-donaciones.pdf",
    "type": "application/pdf",
    "size": 120183,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/medical",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Medical/inventario_Medical_lista_de_requerimientos_donaciones.pdf",
    "ratAreaFolder": "Medical",
    "ratPdfTitle": "Medical lista de requerimientos donaciones"
  },
  {
    "id": "grunenthal-rat-inventario-primary-care-beyond-inscripcion-de-medicos",
    "name": "inventario_Primary_Care_-_Beyond__Inscripción_de_médicos..pdf",
    "displayName": "inventario_Primary_Care_-_Beyond__Inscripción_de_médicos.",
    "path": "/client/grunenthal/rat/primary-care/inventario-primary-care-beyond-inscripcion-de-medicos.pdf",
    "type": "application/pdf",
    "size": 112428,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/primary-care",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Primary Care/inventario_Primary_Care_-_Beyond__Inscripción_de_médicos..pdf",
    "ratAreaFolder": "Primary Care",
    "ratPdfTitle": "Primary Care - Beyond Inscripcion de medicos"
  },
  {
    "id": "grunenthal-rat-inventario-primary-care-carta-invitacion-de-medicos",
    "name": "inventario_Primary_Care_-_Carta_Invitación_de_médicos.pdf",
    "displayName": "inventario_Primary_Care_-_Carta_Invitación_de_médicos",
    "path": "/client/grunenthal/rat/primary-care/inventario-primary-care-carta-invitacion-de-medicos.pdf",
    "type": "application/pdf",
    "size": 128524,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/primary-care",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Primary Care/inventario_Primary_Care_-_Carta_Invitación_de_médicos.pdf",
    "ratAreaFolder": "Primary Care",
    "ratPdfTitle": "Primary Care - Carta Invitacion de medicos"
  },
  {
    "id": "grunenthal-rat-inventario-primary-care-registro-de-medicos-para-invitaciones-o-becas-a-congresos",
    "name": "inventario_Primary_Care_-_Registro_de_médicos_para_invitaciones_o_becas_a_congresos.pdf",
    "displayName": "inventario_Primary_Care_-_Registro_de_médicos_para_invitaciones_o_becas_a_congresos",
    "path": "/client/grunenthal/rat/primary-care/inventario-primary-care-registro-de-medicos-para-invitaciones-o-becas-a-congresos.pdf",
    "type": "application/pdf",
    "size": 112638,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/primary-care",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Primary Care/inventario_Primary_Care_-_Registro_de_médicos_para_invitaciones_o_becas_a_congresos.pdf",
    "ratAreaFolder": "Primary Care",
    "ratPdfTitle": "Primary Care - Registro de medicos para invitaciones o becas a congresos"
  },
  {
    "id": "grunenthal-rat-inventario-primary-care-solicitud-de-congreso-internacional",
    "name": "inventario_Primary_Care_-_Solicitud_de_Congreso_internacional.pdf",
    "displayName": "inventario_Primary_Care_-_Solicitud_de_Congreso_internacional",
    "path": "/client/grunenthal/rat/primary-care/inventario-primary-care-solicitud-de-congreso-internacional.pdf",
    "type": "application/pdf",
    "size": 116630,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/primary-care",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Primary Care/inventario_Primary_Care_-_Solicitud_de_Congreso_internacional.pdf",
    "ratAreaFolder": "Primary Care",
    "ratPdfTitle": "Primary Care - Solicitud de Congreso internacional"
  },
  {
    "id": "grunenthal-rat-inventario-regulatorio-base-de-datos-para-registro-ante-autoridad-sanitaria",
    "name": "inventario_Regulatorio_-_Base_de_datos_para_registro_ante_autoridad_sanitaria._.pdf",
    "displayName": "inventario_Regulatorio_-_Base_de_datos_para_registro_ante_autoridad_sanitaria._",
    "path": "/client/grunenthal/rat/regulatorio/inventario-regulatorio-base-de-datos-para-registro-ante-autoridad-sanitaria.pdf",
    "type": "application/pdf",
    "size": 124249,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/regulatorio",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Regulatorio/inventario_Regulatorio_-_Base_de_datos_para_registro_ante_autoridad_sanitaria._.pdf",
    "ratAreaFolder": "Regulatorio",
    "ratPdfTitle": "Regulatorio - Base de datos para registro ante autoridad sanitaria"
  },
  {
    "id": "grunenthal-rat-inventario-ventas-internas-informacion-sell-out",
    "name": "inventario_Ventas_Internas_-_Información_Sell-out.pdf",
    "displayName": "inventario_Ventas_Internas_-_Información_Sell-out",
    "path": "/client/grunenthal/rat/ventas-internas/inventario-ventas-internas-informacion-sell-out.pdf",
    "type": "application/pdf",
    "size": 109558,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/ventas-internas",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Ventas Internas/inventario_Ventas_Internas_-_Información_Sell-out.pdf",
    "ratAreaFolder": "Ventas Internas",
    "ratPdfTitle": "Ventas Internas - Informacion Sell-out"
  },
  {
    "id": "grunenthal-davara-training-infografia-seis-consejos-grt",
    "name": "Infografia_Seis Consejos_GRT.pdf",
    "displayName": "Infografia_Seis Consejos_GRT",
    "path": "/client/grunenthal/training/infografia-seis-consejos-grt.pdf",
    "type": "application/pdf",
    "size": 1730615,
    "module": "davara-training",
    "category": "training-resource",
    "folder": "training",
    "extension": "pdf",
    "sourceRelativePath": "Material de capacitación/Infografia_Seis Consejos_GRT.pdf"
  },
  {
    "id": "grunenthal-davara-training-infografia-phising-grt",
    "name": "Infografía _Phising_ GRT.pdf",
    "displayName": "Infografía _Phising_ GRT",
    "path": "/client/grunenthal/training/infografia-phising-grt.pdf",
    "type": "application/pdf",
    "size": 359655,
    "module": "davara-training",
    "category": "training-resource",
    "folder": "training",
    "extension": "pdf",
    "sourceRelativePath": "Material de capacitación/Infografía _Phising_ GRT.pdf"
  },
  {
    "id": "grunenthal-davara-training-infografia-arco-grt",
    "name": "Infografía_ARCO_GRT.pdf",
    "displayName": "Infografía_ARCO_GRT",
    "path": "/client/grunenthal/training/infografia-arco-grt.pdf",
    "type": "application/pdf",
    "size": 1179198,
    "module": "davara-training",
    "category": "training-resource",
    "folder": "training",
    "extension": "pdf",
    "sourceRelativePath": "Material de capacitación/Infografía_ARCO_GRT.pdf"
  },
  {
    "id": "grunenthal-davara-training-infografia-datospersonales-grt",
    "name": "Infografía_DatosPersonales_GRT.pdf",
    "displayName": "Infografía_DatosPersonales_GRT",
    "path": "/client/grunenthal/training/infografia-datospersonales-grt.pdf",
    "type": "application/pdf",
    "size": 369141,
    "module": "davara-training",
    "category": "training-resource",
    "folder": "training",
    "extension": "pdf",
    "sourceRelativePath": "Material de capacitación/Infografía_DatosPersonales_GRT.pdf"
  },
  {
    "id": "grunenthal-davara-training-infografia-principios-lfpdppp-grt",
    "name": "Infografía_Principios LFPDPPP_GRT.pdf",
    "displayName": "Infografía_Principios LFPDPPP_GRT",
    "path": "/client/grunenthal/training/infografia-principios-lfpdppp-grt.pdf",
    "type": "application/pdf",
    "size": 419949,
    "module": "davara-training",
    "category": "training-resource",
    "folder": "training",
    "extension": "pdf",
    "sourceRelativePath": "Material de capacitación/Infografía_Principios LFPDPPP_GRT.pdf"
  },
  {
    "id": "grunenthal-privacy-notices-manualap-grunentha-davara-v5",
    "name": "ManualAP_Grünentha Davara v5.docx",
    "displayName": "ManualAP_Grünentha Davara v5",
    "path": "/client/grunenthal/privacy-notices/manualap-grunentha-davara-v5.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 166062,
    "module": "privacy-notices",
    "category": "privacy-notice",
    "folder": "privacy-notices",
    "extension": "docx",
    "sourceRelativePath": "ManualAP_Grünentha Davara v5.docx"
  },
  {
    "id": "grunenthal-privacy-notices-manualap-grunentha-davara-v6",
    "name": "ManualAP_Grünentha Davara v6.docx",
    "displayName": "ManualAP_Grünentha Davara v6",
    "path": "/client/grunenthal/privacy-notices/manualap-grunentha-davara-v6.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 165781,
    "module": "privacy-notices",
    "category": "privacy-notice",
    "folder": "privacy-notices",
    "extension": "docx",
    "sourceRelativePath": "ManualAP_Grünentha Davara v6.docx"
  },
  {
    "id": "grunenthal-dpo-acta-designacion-de-miembros-del-departamento-de-datos-personales-de-grunenthal",
    "name": "Acta designación de miembros del Departamento de Datos Personales de Grünenthal.docx",
    "displayName": "Acta designación de miembros del Departamento de Datos Personales de Grünenthal",
    "path": "/client/grunenthal/dpo/acta-designacion-de-miembros-del-departamento-de-datos-personales-de-grunenthal.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 72437,
    "module": "dpo",
    "category": "dpo-reference",
    "folder": "dpo",
    "extension": "docx",
    "sourceRelativePath": "PolíticasGRT_Davara/Departamento de Datos Personales/Acta designación de miembros del Departamento de Datos Personales de Grünenthal.docx"
  },
  {
    "id": "grunenthal-dpo-manualdeldepartamento-grunenthal-davara-v2",
    "name": "ManualDelDepartamento_Grünenthal  davara v2.docx",
    "displayName": "ManualDelDepartamento_Grünenthal  davara v2",
    "path": "/client/grunenthal/dpo/manualdeldepartamento-grunenthal-davara-v2.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 100218,
    "module": "dpo",
    "category": "dpo-reference",
    "folder": "dpo",
    "extension": "docx",
    "sourceRelativePath": "PolíticasGRT_Davara/Departamento de Datos Personales/ManualDelDepartamento_Grünenthal  davara v2.docx"
  },
  {
    "id": "grunenthal-arco-rights-manualderechosarco-grunenthal-davara-v2",
    "name": "ManualDerechosARCO_Grünenthal davara v2.docx",
    "displayName": "ManualDerechosARCO_Grünenthal davara v2",
    "path": "/client/grunenthal/arco/manualderechosarco-grunenthal-davara-v2.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 11636669,
    "module": "arco-rights",
    "category": "arco-procedure-evidence",
    "folder": "arco",
    "extension": "docx",
    "sourceRelativePath": "PolíticasGRT_Davara/DerechosARCO/ManualDerechosARCO_Grünenthal davara v2.docx"
  },
  {
    "id": "grunenthal-arco-rights-matriz-de-control-y-seguimiento-del-ejercicio-de-derechos-arco",
    "name": "Matriz de Control y seguimiento del Ejercicio de Derechos ARCO.xlsx",
    "displayName": "Matriz de Control y seguimiento del Ejercicio de Derechos ARCO",
    "path": "/client/grunenthal/arco/matriz-de-control-y-seguimiento-del-ejercicio-de-derechos-arco.xlsx",
    "type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "size": 79452,
    "module": "arco-rights",
    "category": "arco-procedure-evidence",
    "folder": "arco",
    "extension": "xlsx",
    "sourceRelativePath": "PolíticasGRT_Davara/DerechosARCO/Matriz de Control y seguimiento del Ejercicio de Derechos ARCO.xlsx"
  },
  {
    "id": "grunenthal-data-policies-lineamientos-en-materia-de-datos-personales-para-area-de-comex-grunenthal",
    "name": "Lineamientos en materia de datos personales para área de COMEX Grünenthal.docx",
    "displayName": "Lineamientos en materia de datos personales para área de COMEX Grünenthal",
    "path": "/client/grunenthal/policies/lineamientos/lineamientos-en-materia-de-datos-personales-para-area-de-comex-grunenthal.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 67685,
    "module": "data-policies",
    "category": "data-policy-evidence",
    "folder": "policies/lineamientos",
    "extension": "docx",
    "sourceRelativePath": "PolíticasGRT_Davara/Lineamientos para áreas relevantes/Lineamientos en materia de datos personales para área de COMEX Grünenthal.docx"
  },
  {
    "id": "grunenthal-data-policies-lineamientos-en-materia-de-datos-personales-para-area-de-human-resources-grunenthal",
    "name": "Lineamientos en materia de datos personales para área de Human Resources Grünenthal.docx",
    "displayName": "Lineamientos en materia de datos personales para área de Human Resources Grünenthal",
    "path": "/client/grunenthal/policies/lineamientos/lineamientos-en-materia-de-datos-personales-para-area-de-human-resources-grunenthal.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 69593,
    "module": "data-policies",
    "category": "data-policy-evidence",
    "folder": "policies/lineamientos",
    "extension": "docx",
    "sourceRelativePath": "PolíticasGRT_Davara/Lineamientos para áreas relevantes/Lineamientos en materia de datos personales para área de Human Resources Grünenthal.docx"
  },
  {
    "id": "grunenthal-data-policies-lineamientos-en-materia-de-datos-personales-para-area-de-medical-de-grunenthal",
    "name": "Lineamientos en materia de datos personales para área de Medical de Grünenthal.docx",
    "displayName": "Lineamientos en materia de datos personales para área de Medical de Grünenthal",
    "path": "/client/grunenthal/policies/lineamientos/lineamientos-en-materia-de-datos-personales-para-area-de-medical-de-grunenthal.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 66023,
    "module": "data-policies",
    "category": "data-policy-evidence",
    "folder": "policies/lineamientos",
    "extension": "docx",
    "sourceRelativePath": "PolíticasGRT_Davara/Lineamientos para áreas relevantes/Lineamientos en materia de datos personales para área de Medical de Grünenthal.docx"
  },
  {
    "id": "grunenthal-data-policies-lineamientos-farmacovigilancia-davara-v1",
    "name": "Lineamientos_Farmacovigilancia Davara v1.docx",
    "displayName": "Lineamientos_Farmacovigilancia Davara v1",
    "path": "/client/grunenthal/policies/lineamientos/lineamientos-farmacovigilancia-davara-v1.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 82564,
    "module": "data-policies",
    "category": "data-policy-evidence",
    "folder": "policies/lineamientos",
    "extension": "docx",
    "sourceRelativePath": "PolíticasGRT_Davara/Lineamientos para áreas relevantes/Lineamientos_Farmacovigilancia Davara v1.docx"
  },
  {
    "id": "grunenthal-third-party-contracts-1-cuestionario-de-proveedores",
    "name": "1. Cuestionario de Proveedores..docx",
    "displayName": "1. Cuestionario de Proveedores.",
    "path": "/client/grunenthal/third-party-contracts/1-cuestionario-de-proveedores.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 130988,
    "module": "third-party-contracts",
    "category": "third-party-contract",
    "folder": "third-party-contracts",
    "extension": "docx",
    "sourceRelativePath": "PolíticasGRT_Davara/Relaciones con Terceros/1. Cuestionario de Proveedores..docx"
  },
  {
    "id": "grunenthal-third-party-contracts-analisisderelacionesgrunenthal",
    "name": "AnálisisDeRelacionesGrünenthal  29-06-26.docx",
    "displayName": "AnálisisDeRelacionesGrünenthal 29-06-26",
    "path": "/client/grunenthal/third-party-contracts/analisisderelacionesgrunenthal.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 151184,
    "module": "third-party-contracts",
    "category": "third-party-contract",
    "folder": "third-party-contracts",
    "extension": "docx",
    "sourceRelativePath": "PolíticasGRT_Davara/Relaciones con Terceros/AnálisisDeRelacionesGrünenthal  29-06-26.docx"
  },
  {
    "id": "grunenthal-third-party-contracts-manualderelaciones-grunenthal-davara-v2",
    "name": "ManualDeRelaciones_Grünenthal  davara v2.docx",
    "displayName": "ManualDeRelaciones_Grünenthal  davara v2",
    "path": "/client/grunenthal/third-party-contracts/manualderelaciones-grunenthal-davara-v2.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 232636,
    "module": "third-party-contracts",
    "category": "third-party-contract",
    "folder": "third-party-contracts",
    "extension": "docx",
    "sourceRelativePath": "PolíticasGRT_Davara/Relaciones con Terceros/ManualDeRelaciones_Grünenthal  davara v2.docx"
  },
  {
    "id": "grunenthal-security-system-carta-empleados-pdp-grt",
    "name": "Carta Empleados PDP GRT.docx",
    "displayName": "Carta Empleados PDP GRT",
    "path": "/client/grunenthal/security-system/carta-empleados-pdp-grt.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 75841,
    "module": "security-system",
    "category": "security-system-policy",
    "folder": "security-system",
    "extension": "docx",
    "sourceRelativePath": "PolíticasGRT_Davara/Seguridad/Carta Empleados PDP GRT.docx"
  },
  {
    "id": "grunenthal-security-system-politica-eipd-grt",
    "name": "Política EIPD_ GRT.docx",
    "displayName": "Política EIPD_ GRT",
    "path": "/client/grunenthal/security-system/politica-eipd-grt.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 1054337,
    "module": "security-system",
    "category": "security-system-policy",
    "folder": "security-system",
    "extension": "docx",
    "sourceRelativePath": "PolíticasGRT_Davara/Seguridad/Política EIPD_ GRT.docx"
  },
  {
    "id": "grunenthal-security-system-politica-sgsdp-grt",
    "name": "Política SGSDP _ GRT .docx",
    "displayName": "Política SGSDP _ GRT ",
    "path": "/client/grunenthal/security-system/politica-sgsdp-grt.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 217029,
    "module": "security-system",
    "category": "security-system-policy",
    "folder": "security-system",
    "extension": "docx",
    "sourceRelativePath": "PolíticasGRT_Davara/Seguridad/Política SGSDP _ GRT .docx"
  },
  {
    "id": "grunenthal-security-system-politica-de-vulneraciones-de-seguridad-de-grt",
    "name": "Política de Vulneraciones de Seguridad de GRT.docx",
    "displayName": "Política de Vulneraciones de Seguridad de GRT",
    "path": "/client/grunenthal/security-system/politica-de-vulneraciones-de-seguridad-de-grt.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 237409,
    "module": "security-system",
    "category": "security-system-policy",
    "folder": "security-system",
    "extension": "docx",
    "sourceRelativePath": "PolíticasGRT_Davara/Seguridad/Política de Vulneraciones de Seguridad de GRT.docx"
  },
  {
    "id": "grunenthal-data-policies-analisisbaseslegalesgrunenthal",
    "name": "AnálisisBasesLegalesGrünenthal .docx",
    "displayName": "AnálisisBasesLegalesGrünenthal ",
    "path": "/client/grunenthal/policies/general/analisisbaseslegalesgrunenthal.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 90067,
    "module": "data-policies",
    "category": "data-policy-evidence",
    "folder": "policies/general",
    "extension": "docx",
    "sourceRelativePath": "PolíticasGRT_Davara/Varios/AnálisisBasesLegalesGrünenthal .docx"
  },
  {
    "id": "grunenthal-data-policies-politica-general-pdp-grt",
    "name": "Política General PDP_ GRT.docx",
    "displayName": "Política General PDP_ GRT",
    "path": "/client/grunenthal/policies/general/politica-general-pdp-grt.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 57616,
    "module": "data-policies",
    "category": "data-policy-evidence",
    "folder": "policies/general",
    "extension": "docx",
    "sourceRelativePath": "PolíticasGRT_Davara/Varios/Política General PDP_ GRT.docx"
  },
  {
    "id": "grunenthal-data-policies-politicadeconservaciongrt",
    "name": "PolíticaDeConservaciónGRT.docx",
    "displayName": "PolíticaDeConservaciónGRT",
    "path": "/client/grunenthal/policies/general/politicadeconservaciongrt.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 73823,
    "module": "data-policies",
    "category": "data-policy-evidence",
    "folder": "policies/general",
    "extension": "docx",
    "sourceRelativePath": "PolíticasGRT_Davara/Varios/PolíticaDeConservaciónGRT.docx"
  },
  {
    "id": "grunenthal-data-policies-copia-de-grt-hq-sop-proc-006916-mexico-davara-v1-1",
    "name": "Copia de GRT_HQ SOP_PROC-006916_México _ Davara v1 (1).docm",
    "displayName": "Copia de GRT_HQ SOP_PROC-006916_México _ Davara v1 (1)",
    "path": "/client/grunenthal/policies/global/copia-de-grt-hq-sop-proc-006916-mexico-davara-v1-1.docm",
    "type": "application/vnd.ms-word.document.macroEnabled.12",
    "size": 61372,
    "module": "data-policies",
    "category": "data-policy-evidence",
    "folder": "policies/global",
    "extension": "docm",
    "sourceRelativePath": "PolíticasGlobalesGRT/Copia de GRT_HQ SOP_PROC-006916_México _ Davara v1 (1).docm"
  },
  {
    "id": "grunenthal-data-policies-grt-proc-003162-davara-v1",
    "name": "GRT_PROC_003162_ davara v1.docx",
    "displayName": "GRT_PROC_003162_ davara v1",
    "path": "/client/grunenthal/policies/global/grt-proc-003162-davara-v1.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 62547,
    "module": "data-policies",
    "category": "data-policy-evidence",
    "folder": "policies/global",
    "extension": "docx",
    "sourceRelativePath": "PolíticasGlobalesGRT/GRT_PROC_003162_ davara v1.docx"
  },
  {
    "id": "grunenthal-data-policies-grt-proc-003298-data-subject-requests-davarav1",
    "name": "GRT_PROC_003298_Data Subject Requests davarav1 .docm",
    "displayName": "GRT_PROC_003298_Data Subject Requests davarav1 ",
    "path": "/client/grunenthal/policies/global/grt-proc-003298-data-subject-requests-davarav1.docm",
    "type": "application/vnd.ms-word.document.macroEnabled.12",
    "size": 78245,
    "module": "data-policies",
    "category": "data-policy-evidence",
    "folder": "policies/global",
    "extension": "docm",
    "sourceRelativePath": "PolíticasGlobalesGRT/GRT_PROC_003298_Data Subject Requests davarav1 .docm"
  },
  {
    "id": "grunenthal-data-policies-grt-proc-7000-retention-of-personal-data-en-released-in-mcl-es-419-davara-v1",
    "name": "GRT_PROC_7000_Retention of personal data_EN_released in MCL es-419  davara v1.docx",
    "displayName": "GRT_PROC_7000_Retention of personal data_EN_released in MCL es-419  davara v1",
    "path": "/client/grunenthal/policies/global/grt-proc-7000-retention-of-personal-data-en-released-in-mcl-es-419-davara-v1.docx",
    "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "size": 59514,
    "module": "data-policies",
    "category": "data-policy-evidence",
    "folder": "policies/global",
    "extension": "docx",
    "sourceRelativePath": "PolíticasGlobalesGRT/GRT_PROC_7000_Retention of personal data_EN_released in MCL es-419  davara v1.docx"
  },
  {
    "id": "grunenthal-rat-inventario-farmacovigilancia-casos-reportados-argus-oracle",
    "name": "inventario_Casos_Reportados_Argus_Oracle.pdf",
    "displayName": "inventario_Casos_Reportados_Argus_Oracle",
    "path": "/client/grunenthal/rat/farmacovigilancia/inventario-farmacovigilancia-casos-reportados-argus-oracle.pdf",
    "type": "application/pdf",
    "size": 69663,
    "module": "rat",
    "category": "rat-inventory",
    "folder": "rat/farmacovigilancia",
    "extension": "pdf",
    "sourceRelativePath": "InventariosDatos Personales/Farmacovigilancia/inventario_Casos_Reportados_Argus_Oracle.pdf",
    "ratAreaFolder": "Farmacovigilancia",
    "ratPdfTitle": "Farmacovigilancia - Casos Reportados (Argus - Oracle)"
  },
  {
    "id": "grunenthal-rat-inventarios-rat-export",
    "name": "inventarios-rat-2025-11-20T00-19-05-360Z (2).json",
    "displayName": "inventarios-rat-2025-11-20T00-19-05-360Z (2)",
    "path": "/client/grunenthal/rat/source/inventarios-rat-export.json",
    "type": "application/json",
    "size": 6182942,
    "module": "rat",
    "category": "rat-source",
    "folder": "rat/source",
    "extension": "json",
    "sourceRelativePath": "inventarios-rat-2025-11-20T00-19-05-360Z (2).json"
  }
]

export function getGrunenthalAssetsByModule(module: GrunenthalAssetModule) {
  return GRUNENTHAL_DOCUMENT_MANIFEST.filter((asset) => asset.module === module)
}

export function getGrunenthalAsset(assetId: string) {
  return GRUNENTHAL_DOCUMENT_MANIFEST.find((asset) => asset.id === assetId) || null
}
