const { describe, it } = require("node:test")
const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const registrationSourcePath = path.join(__dirname, "..", "app", "third-party-contracts", "registration", "page.tsx")
const documentsSourcePath = path.join(__dirname, "..", "app", "third-party-contracts", "documents", "page.tsx")

describe("UI contratos con terceros - documentos asociados", () => {
  it("en registro separa vista previa modal y descarga de contratos asociados", () => {
    const source = fs.readFileSync(registrationSourcePath, "utf8")

    assert.match(source, /FilePreviewDialog/)
    assert.match(source, /canOfferFilePreview/)
    assert.match(source, /previewContractAttachment/)
    assert.match(source, /downloadContractAttachment/)
    assert.match(source, /clauseComplianceBadges/)
    assert.match(source, /Análisis de cláusula/)
    assert.match(source, /Descargar/)
    assert.match(source, /setPreviewAttachmentFile/)
  })

  it("en documentos ofrece ver y descargar para contratos y anexos", () => {
    const source = fs.readFileSync(documentsSourcePath, "utf8")

    assert.match(source, /FilePreviewDialog/)
    assert.match(source, /canOfferFilePreview/)
    assert.match(source, /previewStoredContract/)
    assert.match(source, /downloadStoredContract/)
    assert.match(source, /previewContractAttachment/)
    assert.match(source, /downloadContractAttachment/)
    assert.match(source, /analysisContract/)
    assert.match(source, /visibleContractHistory/)
    assert.match(source, /visibleUploadedContracts/)
    assert.match(source, /isCompiledAnalysisContract/)
    assert.match(source, /isGrtSeededFile/)
    assert.match(source, /GRUNENTHAL_THIRD_PARTY_ANALYSIS_MATRIX/)
    assert.match(source, /filteredMatrixRows/)
    assert.match(source, /Matriz del análisis de relaciones/)
    assert.match(source, /filteredUploadedContracts/)
    assert.match(source, /upsertAuditReminderByReferenceKey/)
    assert.match(source, /generateAllNotifications/)
    assert.match(source, /Actualizar/)
    assert.match(source, /Programar recordatorio/)
    assert.match(source, /monthly/)
    assert.match(source, /quarterly/)
    assert.match(source, /semiannual/)
    assert.match(source, /annual/)
    assert.match(source, /Ver análisis/)
    assert.match(source, /Análisis del contrato/)
    assert.match(source, /sourceFolder/)
    assert.match(source, /clauseComplianceBadges/)
    assert.match(source, /Resultado de análisis/)
    assert.match(source, /Cláusula revisada/)
    assert.match(source, /Recomendación/)
    assert.match(source, /Descargar/)
    assert.match(source, /GRUNENTHAL_THIRD_PARTY_MODEL_CLAUSES/)
    assert.match(source, /Modelos validados del Apéndice 1/)
    assert.match(source, /Validada/)
    assert.doesNotMatch(source, /clause-representantes/)
    assert.doesNotMatch(source, /C\\.5 NO TRATAMIENTO/)
  })
})
