const { describe, it } = require("node:test")
const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const registrationSourcePath = path.join(__dirname, "..", "app", "third-party-contracts", "registration", "page.tsx")
const documentsSourcePath = path.join(__dirname, "..", "app", "third-party-contracts", "documents", "page.tsx")

describe("UI contratos con terceros - documentos asociados", () => {
  it("en registro separa vista previa modal y descarga de contratos asociados", () => {
    const source = fs.readFileSync(registrationSourcePath, "utf8")

    assert.match(source, /FilePreviewDialog/)
    assert.match(source, /canOfferFilePreview/)
    assert.match(source, /previewContractAttachment/)
    assert.match(source, /downloadContractAttachment/)
    assert.match(source, /clauseComplianceBadges/)
    assert.match(source, /Análisis de cláusula/)
    assert.match(source, /Descargar/)
    assert.match(source, /setPreviewAttachmentFile/)
  })

  it("en documentos ofrece ver y descargar para contratos y anexos", () => {
    const source = fs.readFileSync(documentsSourcePath, "utf8")

    assert.match(source, /FilePreviewDialog/)
    assert.match(source, /canOfferFilePreview/)
    assert.match(source, /previewContractAttachment/)
    assert.match(source, /downloadContractAttachment/)
    assert.match(source, /analysisContract/)
    assert.match(source, /visibleContractHistory/)
    assert.match(source, /isCompiledAnalysisContract/)
    assert.match(source, /GRUNENTHAL_THIRD_PARTY_ANALYSIS_MATRIX/)
    assert.match(source, /GRUNENTHAL_GRT_CONTRACT_DOCUMENTS/)
    assert.match(source, /GRUNENTHAL_INDIVIDUAL_THIRD_PARTY_RECORDS/)
    assert.match(source, /buildFallbackContractFromGrtDocument/)
    assert.match(source, /buildFallbackContractFromIndividualAnalysis/)
    assert.match(source, /fallbackFromAnalysis/)
    assert.match(source, /filteredMatrixRows/)
    assert.match(source, /getPrimaryContractAttachment/)
    assert.match(source, /definition\)\.toLowerCase\(\) === "principal"/)
    assert.match(source, /publicPath/)
    assert.match(source, /contractAttachment/)
    assert.match(source, /Análisis de cláusula/)
    assert.match(source, /value="contracts"/)
    assert.match(source, /rounded-2xl bg-\[#edf4ff\]/)
    assert.match(source, /Contratos analizados/)
    assert.doesNotMatch(source, /TabsList className="[^"]*sticky/)
    assert.doesNotMatch(source, /value="matrix"/)
    assert.doesNotMatch(source, /value="uploaded"/)
    assert.doesNotMatch(source, />Matriz</)
    assert.doesNotMatch(source, />Acción</)
    assert.doesNotMatch(source, /previewStoredContract/)
    assert.doesNotMatch(source, /downloadStoredContract/)
    assert.match(source, /upsertAuditReminderByReferenceKey/)
    assert.match(source, /generateAllNotifications/)
    assert.match(source, /Actualizar/)
    assert.match(source, /Programar recordatorio/)
    assert.match(source, /monthly/)
    assert.match(source, /quarterly/)
    assert.match(source, /semiannual/)
    assert.match(source, /annual/)
    assert.match(source, /Ver análisis/)
    assert.match(source, /Análisis del contrato/)
    assert.match(source, /sourceFolder/)
    assert.match(source, /clauseComplianceBadges/)
    assert.match(source, /Agregar cláusula/)
    assert.doesNotMatch(source, /Cláusula N\/A/)
    assert.match(source, /Resultado regulatorio/)
    assert.match(source, /Cláusula revisada/)
    assert.match(source, /Recomendación/)
    assert.match(source, /Descargar/)
    assert.match(source, /GRUNENTHAL_THIRD_PARTY_MODEL_CLAUSES/)
    assert.match(source, /GRUNENTHAL_THIRD_PARTY_MODEL_CONTRACTS/)
    assert.match(source, /Modelos validados del Apéndice 1/)
    assert.match(source, /Contratos modelo del Apéndice 2/)
    assert.match(source, /previewModelContractDocument/)
    assert.match(source, /openTemplateTextDialog/)
    assert.match(source, /downloadModelContractDocx/)
    assert.match(source, /downloadModelContractText/)
    assert.match(source, /Ver documento/)
    assert.match(source, /Ver texto/)
    assert.match(source, /Descargar DOCX/)
    assert.match(source, /Descargar TXT/)
    assert.doesNotMatch(source, /Contrato de Remisión \(R→E\)/)
    assert.doesNotMatch(source, /Contrato de Transferencia \(R→R\)/)
    assert.doesNotMatch(source, /Responsable–Persona Encargada/)
    assert.doesNotMatch(source, /Responsable–Responsable/)
    assert.match(source, /Validada/)
    assert.doesNotMatch(source, /clause-representantes/)
    assert.doesNotMatch(source, /C\\.5 NO TRATAMIENTO/)
  })
})
